### ISSUE TITLE
Missin bpy.context attributes

### ISSUE THREAD

**Issue by bitflak** [svenfraeys/SublimeBlender#7]
If you run print(bpy.context.active_object) from sublime, blender says:

AttributeError: 'Context' object has no attribute 'active_object'

i am new to python, so I don't know how to solve it. but in line 91 in your code you passing globals() and locals() to the exec() function:

exec(compile(open(scriptpath).read(), scriptpath, 'exec'), globals(), locals() )

and they return the current global and local dictionary, respectively to the current module. It seems to be http.server.BaseHTTPRequestHandler and not bpy, or am I wrong?

I am using Blender 2.72

**Comment by florianfelix** [comment]
hoi. i am seeing the same 'problem' here.

this is the script in sublime:


>import bpy
print(bpy.context.active_object.name)


this is the output of the blender console:

> 127.0.0.1 - - [02/Mar/2017 14:02:03] "GET /?scriptpath=%2Fhome%2Ffelix%2Fscripts%2Fblender%2Faddons%2Famanger%2Fstest.py HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/felix/scripts/blender/addons/SublimeBlenderAddon-master/__init__.py", line 102, in blenderExecuteFile
    exec(compile(open(scriptpath).read(), scriptpath, 'exec'), globals(), locals() )
  File "/home/felix/scripts/blender/addons/amanger/stest.py", line 4, in <module>
    print(bpy.context.active_object.name)
AttributeError: 'Context' object has no attribute 'active_object'
127.0.0.1 - - [02/Mar/2017 14:04:53] "GET /?scriptpath=%2Fhome%2Ffelix%2Fscripts%2Fblender%2Faddons%2Famanger%2Fstest.py HTTP/1.1" 200 -

**Comment by skoch9** [comment]
Hi,
the problem you describe is due to threading used by the SublimeBlender plugin. The proper context is not available in the thread which executes your code. A possible solution might be described [here](http://blender.stackexchange.com/questions/51753/context-is-incorrect-python-error).
I did not test it myself as I discovered an IMHO better way do get [autocompletion](https://github.com/mutantbob/pycharm-blender) or [more difficult](https://wiki.blender.org/index.php/User:Ideasman42/BlenderAsPyModule) and [codeexecution](https://wiki.blender.org/index.php/Extensions:2.6/Py/Scripts/Development/Script_Watcher) working.

**Comment by florianfelix** [comment]
thx. will have a look at those.
